spring:
  application:
    name: MiniBankTelegramBot
  main:
    web-application-type: none

bot:
  name: MiniBankTelegramBot
  token: ${BOT_TOKEN}

application:
  middleService:
    url: ${MIDDLE_SERVICE_URL:http://localhost:8080}

logging:
  level:
    org:
      springframework:
        context:
          annotation :DEBUG